global:
    # lotus rpc, supports ws, http, etc.
    lotus_api: "http://your-lotus-node:1234/rpc/v1"
    # lotus rpc authentication token
    auth_token: ""
    # check interval in seconds
    check_interval: 30

    # The following configurations can be overridden in miners configuration, allowing customization for each miner
    # If WindowedPoSt is not detected 10 minutes after deadline starts, consider it problematic
    timeout: 600
    # After 25 minutes from deadline start, stop checking because it's too late
    slient: 1500
    # After a WindowedPoSt issue, sleep for a while to prevent frequent notifications
    sleep_interval: 60
    # Only alert when faulty sectors exceed 100
    faults_sectors: 100
    # apprise_api_server address
    apprise_api_server: https://xxxx.changeme.app/notify
    # Notification channels, supports 100+ types
    # For detailed usage, check the apprise documentation
    recipient_urls:
        - "telegram://changeme:changeme/changeme"
        # - "discord://123456789/abcdefghijklmnopqrstuvwxyz"
miners:
  - miner_id: f01697248
    # timeout: 600
    # slient: 1500
    # sleep_interval: 120
    # faults_sectors: 100
    # apprise_api_server: "http://localhost:8000/notify"
    # recipient_urls:
    #     - "telegram://123456789:abcdefghijklmnopqrstuvwxyz/123456789"
    #     - "discord://123456789/abcdefghijklmnopqrstuvwxyz"
  - miner_id: f01889668
  - miner_id: f01082888
